-- V13: as duas integrações de entrada da seção 9 do CLAUDE.md.
--
-- Nenhuma delas adiciona endpoint: são jobs que chamam os services do domínio, o mesmo caminho
-- da tela. O que o schema precisa ganhar é a memória de "isto eu já processei" — sem ela, uma
-- integração que puxa periodicamente recria cliente e reaplica status a cada execução.

-- ---------- 1) Nectar: a chave de idempotência da sincronização ----------
--
-- O id da oportunidade no Nectar fica no cliente, e é o UNIQUE que garante que o mesmo negócio
-- nunca gera dois clientes. Vai no cliente em vez de numa tabela de controle porque é um dado
-- do cliente: responde "de onde este cadastro veio", que é a pergunta que alguém vai fazer ao
-- ver um cliente que ninguém digitou.
ALTER TABLE cliente ADD COLUMN nectar_oportunidade_id VARCHAR(50);

-- Índice único parcial: no Postgres o UNIQUE comum já ignora NULL, mas o WHERE explícito deixa
-- claro que é esperado que a grande maioria das linhas (todo cliente cadastrado na tela) não
-- tenha valor aqui, e mantém o índice do tamanho do que veio do CRM.
CREATE UNIQUE INDEX uk_cliente_nectar_oportunidade
    ON cliente (nectar_oportunidade_id)
    WHERE nectar_oportunidade_id IS NOT NULL;

-- ---------- 2) Gmail: as mensagens da Coelba já processadas ----------
--
-- Duas funções, e a primeira é o que obriga a tabela a existir: o job lista as mensagens por
-- consulta ("newer_than:7d"), então na execução seguinte as mesmas mensagens voltam. O UNIQUE
-- em mensagem_id é o que impede reaplicar o status. A alternativa seria marcar a mensagem como
-- lida ou rotulá-la no Gmail, o que exigiria escopo de escrita na caixa de e-mail de alguém.
--
-- A segunda função é a auditoria: o status do projeto muda sozinho, então tem de haver onde
-- olhar para responder "por que este projeto foi reprovado ontem às 8h". Guarda o assunto e o
-- resultado da leitura, inclusive dos e-mails que o parser NÃO entendeu — que é justamente o
-- caso que não pode desaparecer em silêncio.
CREATE TABLE email_coelba (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem_id VARCHAR(100) NOT NULL,
    recebido_em TIMESTAMPTZ,
    assunto VARCHAR(500),
    numero_solicitacao VARCHAR(50),
    resultado VARCHAR(30) NOT NULL,
    -- Sem FK para projeto, de propósito, pelo mesmo motivo de historico_status.entidade_id:
    -- com FK, excluir um projeto (DELETE é só do ADMINISTRADOR) passaria a falhar com 409 por
    -- causa da trilha da integração. Preservar a trilha vale mais que a integridade aqui.
    projeto_id BIGINT,
    detalhe VARCHAR(1000),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_email_coelba_mensagem UNIQUE (mensagem_id),
    CONSTRAINT ck_email_coelba_resultado CHECK (resultado IN (
        'APLICADO', 'SEM_ALTERACAO', 'NAO_RECONHECIDO', 'SEM_CORRESPONDENCIA',
        'AMBIGUO', 'TRANSICAO_INVALIDA', 'ERRO'))
);

-- A consulta de diagnóstico é "o que a integração fez ontem" e "o que ela não entendeu".
CREATE INDEX idx_email_coelba_resultado ON email_coelba (resultado, criado_em DESC);
CREATE INDEX idx_email_coelba_projeto ON email_coelba (projeto_id);

-- ---------- 3) O autor das mudanças automáticas ----------
--
-- historico_status.usuario_id é nulável, então a integração poderia gravar nulo. Mas a linha do
-- tempo do projeto ficaria com o autor em branco, indistinguível de um registro importado da
-- planilha — e o projeto inteiro existe porque a ausência de registro era o problema.
--
-- ativo = FALSE não é descuido e sim a proteção: sem senha e inativo, esta conta não entra pelo
-- login nem renova token, e o lookup de analistas (/api/usuarios/lookup?ativo=true, que alimenta
-- os campos de responsável no frontend) filtra por ativo — então ela não aparece como alguém a
-- quem atribuir trabalho. Sem papel nenhum, também nada autorizaria. Os jobs chamam os services
-- direto, sem passar por @PreAuthorize, então não precisam de papel.
INSERT INTO usuario (nome, email, ativo)
VALUES ('Integração automática', 'integracao@conectsol.com', FALSE);
