-- Sincronização de saída para o Nectar: a etapa do CRM passa a seguir o status do SolarSync
-- (22/09/2026). É a integração que faltava da seção 9 do CLAUDE.md, e a que o desenho de eventos
-- deixou mais barata — um @TransactionalEventListener(AFTER_COMMIT), sem tocar em projeto nem em
-- vistoria.
--
-- A tabela tem as mesmas duas funções de email_coelba, e pela mesma razão: a mudança acontece
-- sozinha e não há tela.
--
--  1. Idempotência — antes de mover, consulta-se o último resultado aplicado para o cliente. Se
--     ele já foi posto naquela etapa, não há chamada nenhuma ao CRM.
--  2. Auditoria — sem isto, "por que este cliente está na etapa errada no Nectar?" só teria como
--     resposta o log do servidor, que rotaciona. Guarda inclusive a falha, que é o caso que não
--     pode sumir em silêncio: a movimentação no SolarSync acontece de qualquer jeito (a
--     integração nunca desfaz o status correto), então a única pista de que o CRM ficou para trás
--     é esta linha.
--
-- Como historico_status e email_coelba, NÃO tem endpoint de escrita: só o listener escreve.
-- E como email_coelba, cliente_id NÃO tem FK — com FK, excluir um cliente passaria a falhar com
-- 409 por causa da trilha de uma integração.
CREATE TABLE nectar_etapa_sincronizacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    oportunidade_id VARCHAR(50),
    -- A situação do fluxo do SolarSync que motivou a movimentação (EtapaDoFluxo).
    etapa_fluxo VARCHAR(40) NOT NULL,
    banco BOOLEAN NOT NULL DEFAULT FALSE,
    funil_id BIGINT,
    etapa_id BIGINT,
    etapa_nome VARCHAR(200),
    resultado VARCHAR(30) NOT NULL,
    detalhe VARCHAR(1000),
    ocorrido_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_nectar_sincronizacao_resultado CHECK (resultado IN (
        'APLICADO',          -- o PUT foi feito e o CRM aceitou
        'CONFERENCIA',       -- modo ensaio: teria movido, e não moveu
        'JA_NA_ETAPA',       -- o CRM já estava na etapa certa; nada a fazer
        'SEM_OPORTUNIDADE',  -- cliente cadastrado à mão, sem vínculo com o CRM
        'SEM_MAPEAMENTO',    -- situação do fluxo sem etapa correspondente configurada
        'ERRO'))             -- a API do Nectar recusou ou não respondeu
);

-- As duas consultas da integração: o último resultado do cliente (idempotência) e a fila de
-- reprocessamento das falhas.
CREATE INDEX idx_nectar_sincronizacao_cliente
    ON nectar_etapa_sincronizacao (cliente_id, ocorrido_em DESC);
CREATE INDEX idx_nectar_sincronizacao_erro
    ON nectar_etapa_sincronizacao (resultado) WHERE resultado = 'ERRO';
