-- ---------- RBAC ----------
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha_hash VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE papel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_papel_nome UNIQUE (nome),
    CONSTRAINT ck_papel_nome CHECK (nome IN ('ADMINISTRADOR', 'GESTOR', 'ANALISTA'))
);

CREATE TABLE permissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_permissao_nome UNIQUE (nome)
);

CREATE TABLE usuario_papel (
    usuario_id BIGINT NOT NULL REFERENCES usuario (id),
    papel_id BIGINT NOT NULL REFERENCES papel (id),
    PRIMARY KEY (usuario_id, papel_id)
);

CREATE TABLE papel_permissao (
    papel_id BIGINT NOT NULL REFERENCES papel (id),
    permissao_id BIGINT NOT NULL REFERENCES permissao (id),
    PRIMARY KEY (papel_id, permissao_id)
);

-- ---------- Cliente ----------
CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cidade VARCHAR(100),
    vendedor VARCHAR(150),
    data_pagamento DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_cliente_nome ON cliente (nome);

-- ---------- Pendencia ----------
CREATE TABLE pendencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente (id),
    tipo VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    solicitado_em TIMESTAMPTZ NOT NULL,
    resolvido_em TIMESTAMPTZ,
    responsavel_id BIGINT REFERENCES usuario (id),
    observacao VARCHAR(1000),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_pendencia_tipo CHECK (tipo IN ('TROCA_TITULARIDADE', 'LIGACAO_NOVA', 'EXTENSAO_REDE', 'OUTRA')),
    CONSTRAINT ck_pendencia_status CHECK (status IN ('ABERTA', 'EM_ANDAMENTO', 'RESOLVIDA', 'CANCELADA'))
);
CREATE INDEX idx_pendencia_cliente ON pendencia (cliente_id);
CREATE INDEX idx_pendencia_status ON pendencia (status);

-- ---------- Debito ----------
CREATE TABLE debito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente (id),
    status VARCHAR(20) NOT NULL,
    ultima_consulta_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_debito_cliente UNIQUE (cliente_id),
    CONSTRAINT ck_debito_status CHECK (status IN ('ATIVO', 'QUITADO'))
);

-- ---------- Projeto ----------
CREATE TABLE projeto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente (id),
    tipo_projeto VARCHAR(40) NOT NULL,
    analista_responsavel_id BIGINT REFERENCES usuario (id),
    data_recebimento DATE,
    data_art DATE,
    data_encaminhado DATE,
    status VARCHAR(20) NOT NULL,
    motivo_reprova VARCHAR(1000),
    data_aprovacao DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_projeto_tipo CHECK (tipo_projeto IN ('PADRAO', 'AMPLIACAO', 'AUMENTO_POTENCIA', 'MUDANCA_INVERSOR', 'PROJETO_UMA_PLACA_A_MAIS', 'INVERSORES_SEPARADOS')),
    CONSTRAINT ck_projeto_status CHECK (status IN ('RECEBIDO', 'AGUARDANDO_ENVIO', 'ENCAMINHADO', 'APROVADO', 'REPROVADO', 'REENCAMINHADO'))
);
CREATE INDEX idx_projeto_cliente ON projeto (cliente_id);
CREATE INDEX idx_projeto_status ON projeto (status);

-- ---------- Vistoria ----------
CREATE TABLE vistoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id BIGINT NOT NULL REFERENCES projeto (id),
    data_solicitacao DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    data_resultado DATE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_vistoria_status CHECK (status IN ('SOLICITADA', 'APROVADA', 'REPROVADA'))
);
CREATE INDEX idx_vistoria_projeto ON vistoria (projeto_id);

-- ---------- Unificacao ----------
CREATE TABLE unificacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente (id),
    cidade VARCHAR(100),
    projetista_id BIGINT REFERENCES usuario (id),
    informacoes VARCHAR(1000),
    feita BOOLEAN NOT NULL DEFAULT FALSE,
    desligamento BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_unificacao_cliente ON unificacao (cliente_id);

-- ---------- HistoricoStatus (auditoria genérica) ----------
CREATE TABLE historico_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade_tipo VARCHAR(30) NOT NULL,
    entidade_id BIGINT NOT NULL,
    status_anterior VARCHAR(30),
    status_novo VARCHAR(30) NOT NULL,
    ocorrido_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    usuario_id BIGINT REFERENCES usuario (id),
    CONSTRAINT ck_historico_entidade_tipo CHECK (entidade_tipo IN ('CLIENTE', 'PENDENCIA', 'DEBITO', 'PROJETO', 'VISTORIA', 'UNIFICACAO'))
);
CREATE INDEX idx_historico_entidade ON historico_status (entidade_tipo, entidade_id);
