-- V9: Novos tipos de pendência Coelba solicitados pela operação:
-- AUMENTO_CARGA, MUDANCA_PADRAO, DESMEMBRAMENTO, REGULARIZACAO_CADASTRAL, DEBITO_VINCULADO, ADEQUACAO_TECNICA

ALTER TABLE pendencia DROP CONSTRAINT IF EXISTS ck_pendencia_tipo;

ALTER TABLE pendencia ADD CONSTRAINT ck_pendencia_tipo CHECK (tipo IN (
    'TROCA_TITULARIDADE',
    'LIGACAO_NOVA',
    'EXTENSAO_REDE',
    'AUMENTO_CARGA',
    'MUDANCA_PADRAO',
    'DESMEMBRAMENTO',
    'REGULARIZACAO_CADASTRAL',
    'DEBITO_VINCULADO',
    'ADEQUACAO_TECNICA',
    'OUTRA'
));
